Planetario/Planetario/Controllers/MaterialEducativoController.cs
using System.Web.Mvc;
using Planetario.Handlers;
using Planetario.Models;

namespace Planetario.Controllers
{
    public class MaterialEducativoController : Controller
    {
        public ActionResult AlmacenarNuevoMaterialEducativo()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AlmacenarNuevoMaterialEducativo(MaterialEducativoModel MaterialEducativo)
        {
            ViewBag.ExitoAlmacenar = false;
            try
            {
                if (ModelState.IsValid)
                {
                    MaterialesEducativosHandler AccesoADatos = new MaterialesEducativosHandler();
                    ViewBag.ExitoAlmacenar = AccesoADatos.AlmacenarMaterialEducativo(MaterialEducativo);
                    if(ViewBag.ExitoAlmacenar)
                    {
                        ViewBag.Mensaje = "El material " + MaterialEducativo.Titulo + " fue almacenado con exito 😉";
                        ModelState.Clear();
                    } 
                    else
                    {
                        ViewBag.Mensaje = "Hubo un error en la base de datos ☹";
                    }
                }
                else
                {
                    ViewBag.Mensaje = "El modelo no es valido!";
                }
                return View();
            }
            catch
            {
                ViewBag.Mensaje = "Algo salió mal y no fue posible almacenar el material 😐";
                return View();
            }
        }

        public ActionResult listadoDeMateriales()
        {
            MaterialesEducativosHandler accesoDatos = new MaterialesEducativosHandler();
            ViewBag.materiales = accesoDatos.obtenerMateriales();
            return View();
        }

        [HttpGet]
        public FileResult descargarArchivo(string titulo)
        {
            MaterialesEducativosHandler accesoDatos = new MaterialesEducativosHandler();
            var tupla = accesoDatos.descargarContenido(titulo);
            return File(tupla.Item1, tupla.Item2);
        }

        public ActionResult verMaterial(string nombre)
        {
            MaterialesEducativosHandler accesoDatos = new MaterialesEducativosHandler();
            ViewBag.material = accesoDatos.buscarActividad(nombre);
            ViewBag.materiales = accesoDatos.obtenerTodasLosMaterialesRecomendados(ViewBag.material.PublicoDirigido, ViewBag.material.Categoria);
            return View();
        }

        [HttpGet]
        public FileResult descargarVistaPrevia(string titulo)
        {
            MaterialesEducativosHandler accesoDatos = new MaterialesEducativosHandler();
            var tupla = accesoDatos.descargarVistaPrevia(titulo);
            return File(tupla.Item1, tupla.Item2);
        }

        [HttpGet]
        public ActionResult buscarMaterialesEducativos(string palabra)
        {
            MaterialesEducativosHandler accesoDatos = new MaterialesEducativosHandler();
            ViewBag.materialesUnicos = accesoDatos.obtenerMaterialBuscado(palabra);
            return View();
        }


    }
}

Planetario/Planetario/Views/MaterialEducativo/AlmacenarNuevoMaterialEducativo.cshtml
@model Planetario.Models.MaterialEducativoModel
@{ 
    List<SelectListItem> Categorias = new List<SelectListItem>() {
        new SelectListItem { Text = "Cuerpos del Sistema Solar", Value = "Cuerpos del Sistema Solar" },
        new SelectListItem { Text = "Objetos de Cielo Profundo", Value = "Objetos de Cielo Profundo"  },
        new SelectListItem { Text = "Astronomia", Value = "Astronomia" },
        new SelectListItem { Text = "General", Value = "General" },
    };

    List<SelectListItem> PublicoDirigido = new List<SelectListItem>() {
        new SelectListItem { Text = "Niños", Value = "Niños"},
        new SelectListItem { Text = "Jóvenes", Value = "Jóvenes"},
        new SelectListItem { Text = "Adultos mayores", Value = "Adultos mayores" }
    };
}
<head>
    <link rel="stylesheet" type="text/css" href="~/Utils/css/main.css">
</head>

@if (ViewBag.Mensaje != null)
{
    <h6>@ViewBag.mensaje</h6>
}

<span class="titulo">
    Agregar Material Educativo
</span>

@using (Html.BeginForm("AlmacenarNuevoMaterialEducativo", "MaterialEducativo", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <h4>Ingrese los datos y el material educativo</h4>
    <hr />
    <div class="row">

        <div class="col-6 col-md-6 col-sm-12">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label" })
            <div>
                @Html.TextBoxFor(model => model.Titulo, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>

            @Html.LabelFor(model => model.Categoria, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Categoria, Categorias, "- - -", new { @id = "categoriaPregunta", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Categoria, "", new { @class = "text-danger" })
            </div>

            @Html.LabelFor(model => model.PublicoDirigido, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.PublicoDirigido, PublicoDirigido, "- - -", new { @id = "publicoDirigido", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PublicoDirigido, "", new { @class = "text-danger" })
            </div>


        </div>

        <div class="col-6 col-md-6 col-sm-12">
            @Html.LabelFor(model => model.MaterialArchivo, htmlAttributes: new { @class = "control-label" })
            <br />
            <div >
                @Html.TextBoxFor(model => model.MaterialArchivo, new { type = "file", @class = "alert alert-info" })
                @Html.ValidationMessageFor(model => model.MaterialArchivo, "", new { @class = "text-danger" })
            </div>
            @Html.LabelFor(model => model.ImagenVistaPrevia, new { @class = "control-label" })
            <div >
                @Html.TextBoxFor(model => model.ImagenVistaPrevia, new { type = "file", @class = "alert alert-info" })
                @Html.ValidationMessageFor(model => model.ImagenVistaPrevia, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="row">
        <div>
            <input type="submit" class="btn btn-success" value="Crear" />
            @Html.ActionLink("Volver", "listadoDeMateriales", null, new { @class = "btn btn-secondary" })
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar a Inicio", "InformacionBasica", "Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Planetario/Planetario/Views/MaterialEducativo/buscarMaterialesEducativos.cshtml
@model Planetario.Models.MaterialEducativoModel
@{
    ViewBag.Title = "Materiales";
}

<!DOCTYPE html>
<html>
<head>
    <title>Materiales Educativos</title>
    <meta charset="utf-8" />
    <link rel="stylesheet" type="text/css" href="~/Utils/css/main.css">
</head>
<body>
    <span class="titulo">
        Materiales Educativos
    </span>

    <form method="post" class="navbar-form navbar-right" action="@Url.Action("listadoDeMateriales", "MaterialEducativo")">
        <button type="submit" class="btn btn-secondary"> <span class="fa fa-home" aria-hidden="true"></span> Volver</button>
    </form>


    <table class="table table-hover well">
        <tr>
            <th>ID</th>
            <th>Título</th>
            <th>Público</th>
            <th>Educador</th>
            <th>Ver</th>
        </tr>
        @foreach (var material in ViewBag.materialesUnicos)
        {
            <tr>
                <td>@material.Titulo </td>
                <td>@material.Categoria </td>
                <td>@material.PublicoDirigido</td>
                <td>@material.NombreResponsable (@material.CorreoResponsable)</td>
                <td>
                    <h5>@Html.ActionLink("Ver más", "verMaterial", "MaterialEducativo", new { nombre = material.Titulo.ToString() }, new { @class = "h5" })</h5>
                </td>
            </tr>
        }
    </table>

</body>
</html>

Planetario/Planetario/Views/MaterialEducativo/listadoDeMateriales.cshtml
@model Planetario.Models.MaterialEducativoModel
@{
    ViewBag.Title = "Materiales";
}

<!DOCTYPE html>
<html>
<head>
    <title>Materiales Educativos</title>
    <meta charset="utf-8" />
    <link rel="stylesheet" type="text/css" href="~/Utils/css/main.css">
</head>
<body>
    <span class="titulo">
        Materiales Educativos
    </span>

    <form method="get" class="navbar-form navbar-right" action="@Url.Action("buscarMaterialesEducativos", "MaterialEducativo")">
        <div class="row">
            <div class="col-3 col-md-3 col-sm-2">
                <input type="text" name="palabra" class="form-control" placeholder="Buscar material">
            </div>
            <div class="col-3 col-md-3 col-sm-2">
                <button type="submit" class="btn btn-secondary"> <span class="fa fa-search" aria-hidden="true"></span> Buscar</button>
            </div>
        </div>
    </form>

    <table class="table table-hover well">
        <tr>
            <th>ID</th>
            <th>Título</th>
            <th>Público</th>
            <th>Educador</th>
            <th>Ver</th>
        </tr>
        @foreach (var material in ViewBag.materiales)
        {
            <tr>
                <td>@material.Titulo </td>
                <td>@material.Categoria </td>
                <td>@material.PublicoDirigido</td>
                <td>@material.NombreResponsable (@material.CorreoResponsable)</td>
                <td>
                    <h5>@Html.ActionLink("Ver más", "verMaterial", "MaterialEducativo", new { nombre = material.Titulo.ToString() }, new { @class = "h5" })</h5>
                </td>
            </tr>
        }
    </table>

</body>
</html>

Planetario/Planetario/Views/MaterialEducativo/verMaterial.cshtml
@{
    ViewBag.Title = "Materiales";
}

<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.material.Titulo</title>
    <meta charset="utf-8" />
    <link rel="stylesheet" type="text/css" href="~/Utils/css/main.css">
    <style>
        header,
        section,
        aside {
            margin: 0 1.5% 24px 1.5%;
        }

        section {
            float: left;
            width: 63%;
        }

        aside {
            float: right;
            width: 30%;
        }

        row {
            text-align: center;
        }

        .col {
            margin-bottom: 1em;
        }

        .card {
            margin: 1%;
            border-radius: 15%;
            border-color: #133b5c;
            border-width: .15em;
            box-shadow: 3px 7px #133b5c;
        }

        .site-footer {
            display: none;
        }
    </style>
</head>
<body>
    <div class="row text-center">
        <span class="titulo">@ViewBag.material.Titulo</span>
    </div>
    <section>
        <div class="row">
            <p class="card-title"> <b>Vista previa:</b> </p>
            <img src=https://upload.wikimedia.org/wikipedia/commons/c/c7/Saturn_during_Equinox.jpg>
        </div>
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4 text-center">
                <div class="col">
                    <p><span> <i class="fa fa-check"></i><b>Categoria</b> </span></p>
                    <p> @ViewBag.material.Categoria </p>
                </div>
                <div class="col">
                    <p><span> <i class="fa fa-check"></i><b>Publico Dirigido</b> </span></p>
                    <p> @ViewBag.material.PublicoDirigido </p>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col col-md-4 col-sm-12">
                @Html.ActionLink("Ver", "descargarArchivo",
                         new { titulo = @ViewBag.material.Titulo }
                     )
            </div>
        </div>
    </section>

    <aside>
        <span class="titulo">Materiales Similares:</span>

        @foreach (Planetario.Models.MaterialEducativoModel material in ViewBag.materiales)
        {
            if (ViewBag.material.Titulo != material.Titulo)
            {
                <div class="col">
                    <div class="card">
                        <span class="titulo">                        
                                <i class="fa fa-commenting" aria-hidden="true"></i>                                                       
                            <br />
                            @Html.ActionLink(@material.Titulo, "verMaterial", "MaterialesEducativos", new { nombre = material.Titulo.ToString() }, new { style = "font-size: 30px" })
                        </span>
                        <div class="detallesActividad" , style="text-align:center">
                            <div>
                                <i class="fa fa-angle-right" aria-hidden="true"></i>
                                <b>Publico Dirigido: </b>@material.PublicoDirigido
                            </div>
                            <div>
                                <i class="fa fa-angle-right" aria-hidden="true"></i>
                                <b>Categoria: </b>@material.Categoria
                            </div>                           
                        </div>
                    </div>
                </div>
            }
        }
    </aside>
</body>
</html>