Planetario/Planetario/Controllers/JuegosController.cs
using Planetario.Handlers;
using Planetario.Interfaces;
using System.Web.Mvc;

namespace Planetario.Controllers
{
    public class JuegosController : Controller
    {
        readonly CookiesInterfaz cookiesInterfaz;

        public JuegosController()
        {
            cookiesInterfaz = new CookiesHandler();
        }

        public ActionResult Lista()
        {
            PersonaHandler personasHandler = new PersonaHandler();
            string correoUsuario = cookiesInterfaz.CorreoUsuario();
            string membresia = personasHandler.ObtenerMembresia(correoUsuario);
            ViewBag.Membresia = membresia;
            return View();
        }

        public ActionResult UFO2048()
        {
            return View();
        }

        public ActionResult ETBrain()
        {
            return View();
        }

        public ActionResult ConectaPlanetas()
        {
            return View();
        }

        public ActionResult RapidMath()
        {
            return View();
        }

        public ActionResult SistemaInteractivo()
        {
            return View();
        }

        public ActionResult VideoQuiz()
        {
            return View();
        }
    }
}

Planetario/Planetario/Views/Juegos/ConectaPlanetas.cshtml
<body>
    <span class="titulo">¡Crucigrama Espacial!</span>
    <div class="justify-content-center" style="width:1110px;margin:auto;">
        <iframe width="1110" height="750" frameborder="0" src="https://es.educaplay.com/juego/4591831-el_sistema_solar.html"></iframe>
    </div>
    <hr />
</body>

Planetario/Planetario/Views/Juegos/ETBrain.cshtml
<body>
    <div class="container">
        <div class="">
            <span class="titulo">ET Brain</span>
            <div class="col">
                <div class="justify-content-center" style="width:800px;margin:auto;">
                    <script src="https://cdn.htmlgames.com/embed.js?game=ETBrain&amp;bgcolor=white"></script>
                </div>
            </div>
        </div>
        <hr />
    </div>
</body>

Planetario/Planetario/Views/Juegos/Lista.cshtml
<body>
    <span class="titulo">Juegos educativos</span>

    <p class="text-center">¡Diviértete con juegos educativos y aprende de una forma no tradicional!</p>

    <style>
        .card {
            border: 2px solid #133b5c;
            box-shadow: 0px 0px 2px #133b5c;
        }

            .card:hover {
                box-shadow: 0px 0px 12px #133b5c;
            }
    </style>

    <div class="row rows-cols-md-3 g-4">
        <div class="col">
            <div class="card h-100">
                <img src="~/Utils/images/Juegos/ETGame.jpg" class="card-img-top" style="object-fit: cover; height: 240px;" />
                <div class="card-body">
                    <h5 class="card-title">ET Brain</h5>
                    <p class="card-text">Entrena tu mente con cada uno de los fascinantes minijuegos de ET Brain. Sigue las instrucciones para cada mini juego en este fascinante potenciador mental listo para jugar.</p>
                </div>
                <div class="card-footer">
                    <p>Dificultad: Intermedio</p>
                </div>
                <a href="@Url.Action("ETBrain","Juegos")" class="hidden stretched-link"></a>
            </div>

        </div>
        <div class="col">
            <div class="card h-100">
                <img src="~/Utils/images/Juegos/UFO2048.jpg" class="card-img-top" style="object-fit: cover; height: 240px;" />
                <div class="card-body">
                    <h5 class="card-title">2048 UFO</h5>
                    <p class="card-text">Mueve todas las fichas hacia arriba, abajo, izquierda o derecha. 2 de las mismas baldosas vecinas aumentan de tamaño. Intenta alcanzar la meta indicada.</p>
                </div>
                <div class="card-footer">
                    <p>Dificultad: Intermedio</p>
                </div>

                @if (ViewBag.Membresia == "Lunar" || ViewBag.Membresia == "Solar")
                {
                    <a href="@Url.Action("UFO2048","Juegos")" class="hidden stretched-link"></a>
                }
                else
                {
                    <a href="@Url.Action("Comprar","Membresias")" onclick = "return confirm('¿Quieres adquirir una membresía para poder jugar este juego?')" class="hidden stretched-link"></a>
                }
            </div>

        </div>
        <div class="col">
            <div class="card h-100">
                <img src="~/Utils/images/Juegos/conectaPlanetas.jpg" class="card-img-top" style="object-fit: cover; height: 240px;" />
                <div class="card-body">
                    <h5 class="card-title">¡Crucigrama Espacial!</h5>
                    <p class="card-text">Reconocimiento de las características generales del Sistema Solar y los cuerpos que lo integran, entre ellos la Tierra como un planeta y la Luna como su satélite.</p>
                </div>
                <div class="card-footer">
                    <p>Dificultad: Fácil</p>
                </div>
                <a href="@Url.Action("ConectaPlanetas","Juegos")" class="hidden stretched-link"></a>
            </div>

        </div>
    </div>

    <div class="row rows-cols-md-3 g-4">
        <div class="col">
            <div class="card h-100">
                <img src="~/Utils/images/Juegos/RapidMath.jpg" class="card-img-top" style="object-fit: cover; height: 240px;" />
                <div class="card-body">
                    <h5 class="card-title">Rapid Math</h5>
                    <p class="card-text">Resuelva las operaciones matemáticas lo más rápido posible, antes de que se acabe el tiempo. Toque la respuesta o use la salida del teclado.</p>
                </div>
                <div class="card-footer">
                    <p>Dificultad: Intermedio</p>
                </div>
                <a href="@Url.Action("RapidMath","Juegos")" class="hidden stretched-link"></a>
            </div>

        </div>
        <div class="col">
            <div class="card h-100">
                <img src="~/Utils/images/Juegos/MapaSistema.jpg" class="card-img-top" style="object-fit: cover; height: 240px;" />
                <div class="card-body">
                    <h5 class="card-title">SisteMap Solar</h5>
                    <p class="card-text">Aprende las ubicaciones de los planetas en nuestro Sistema Solar de una forma entretenida!</p>
                </div>
                <div class="card-footer">
                    <p>Dificultad: Fácil</p>
                </div>
                <a href="@Url.Action("SistemaInteractivo","Juegos")" class="hidden stretched-link"></a>
            </div>

        </div>
        <div class="col">
            <div class="card h-100">
                <img src="~/Utils/images/Juegos/VideoQuiz.jpg" class="card-img-top" style="object-fit: cover; height: 240px;" />
                <div class="card-body">
                    <h5 class="card-title">Video Quiz Solar</h5>
                    <p class="card-text">Reconocer las principales características del sistema solar y sus componentes.</p>
                </div>
                <div class="card-footer">
                    <p>Dificultad: Fácil</p>
                </div>
                <a href="@Url.Action("VideoQuiz","Juegos")" class="hidden stretched-link"></a>
            </div>

        </div>
    </div>

</body>

Planetario/Planetario/Views/Juegos/RapidMath.cshtml
<body>
    <div class="container">
        <div class="">
            <span class="titulo">Rapid Math</span>
            <div class="col">
                <div class="justify-content-center" style="width:800px;margin:auto;">
                    <script src="https://cdn.htmlgames.com/embed.js?game=RapidMath&amp;bgcolor=white"></script>
                </div>
            </div>
        </div>
        <hr />
    </div>
</body>

Planetario/Planetario/Views/Juegos/SistemaInteractivo.cshtml
<body>
    <span class="titulo">¡SisteMap Solar!</span>
    <div class="justify-content-center" style="width:1110px;margin:auto;">
        <iframe width="1110" height="750" frameborder="0" src="https://es.educaplay.com/juego/7209539-el_sistema_solar.htmlE"></iframe>
    </div>
    <hr />
</body>

Planetario/Planetario/Views/Juegos/UFO2048.cshtml
<body>
    <div class="container">
        <div class="">
            <span class="titulo">UFO 2048</span>
            <div class="col">
                <div class="justify-content-center" style="width:800px;margin:auto;">
                    <script src="https://cdn.htmlgames.com/embed.js?game=2048UFO&amp;bgcolor=white"></script>
                </div>
            </div>
        </div>
        <hr />
    </div>
</body>

Planetario/Planetario/Views/Juegos/VideoQuiz.cshtml
<body>
    <span class="titulo">¡Video Quiz Solar!</span>
    <div class="justify-content-center" style="width:1110px;margin:auto;">
        <iframe width="1110" height="750" frameborder="0" src="https://es.educaplay.com/juego/5738957-el_universo.html"></iframe>
    </div>
    <hr />
</body>