Planetario/Planetario/Controllers/ActividadesController.cs
using System;
using System.Web.Mvc;
using Planetario.Handlers;
using Planetario.Models;
using System.Collections.Generic;
using Planetario.Interfaces;

namespace Planetario.Controllers
{
    public class ActividadesController : Controller
    {

        private readonly ActividadesInterfaz AccesoDatos;

        public ActividadesController()
        {
            AccesoDatos = new ActividadHandler();
        }

        public ActividadesController(ActividadesInterfaz service)
        {
            AccesoDatos = service;
        }

        public ActionResult CrearActividad()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CrearActividad(ActividadModel actividad, string topicos)
        {
            ViewBag.ExitoAlCrear = false;
            string[] topicosSeleccionados = topicos.Split(';');
            try
            {
                if (ModelState.IsValid)
                {
                    
                    ViewBag.ExitoAlCrear = AccesoDatos.InsertarActividad(actividad);
                    if (ViewBag.ExitoAlCrear)
                    {
                        ViewBag.Message = "La actividad " + actividad.NombreActividad + " fue creada con éxito.";
                        foreach(string topico in topicosSeleccionados)
                        {
                            AccesoDatos.InsertarTopico(actividad.NombreActividad, topico);
                        }
                        ModelState.Clear();
                    } else
                    {
                        ViewBag.Message = "Hubo un error al guardar los datos ingresados.";
                    }
                }
                else
                {
                    ViewBag.Message = "Hay un error en los datos ingresados";
                }
                return View();
            }
            catch
            {
                ViewBag.Message = "Hubo un error al crear el cuestionario " + actividad.NombreActividad;
                return View();
            }
        }

        public ActionResult ListadoDeActividades()
        {

            ViewBag.actividades = AccesoDatos.ObtenerActividadesAprobadas();
            return View();
        }

        public ActionResult VerActividad(string nombreDeLaActividad)
        {
            
            ViewBag.actividad = AccesoDatos.ObtenerActividad(nombreDeLaActividad);
            ViewBag.topicos = AccesoDatos.ObtenerTopicosActividad(nombreDeLaActividad);
            ViewBag.actividades = AccesoDatos.ObtenerActividadesRecomendadas(ViewBag.actividad.PublicoDirigido, ViewBag.actividad.Complejidad);
            ViewBag.entradasDisponibles = AccesoDatos.ObtenerEntradasDisponiblesPorActividad(nombreDeLaActividad);
            ViewBag.asientosRelacionadosActividad = AccesoDatos.ObtenerAsientos(nombreDeLaActividad);
            return View();
        }

        [HttpGet]
        public ActionResult ComprarEntradas(string nombreDeLaActividad)
        {
            ViewBag.actividad = AccesoDatos.ObtenerActividad(nombreDeLaActividad);
            ViewBag.topicos = AccesoDatos.ObtenerTopicosActividad(nombreDeLaActividad);
            ViewBag.actividades = AccesoDatos.ObtenerActividadesRecomendadas(ViewBag.actividad.PublicoDirigido, ViewBag.actividad.Complejidad);
            ViewBag.entradasDisponibles = AccesoDatos.ObtenerEntradasDisponiblesPorActividad(nombreDeLaActividad);
            ViewBag.asientosRelacionadosActividad = AccesoDatos.ObtenerAsientos(nombreDeLaActividad);
            return View();
        }

        [HttpGet]
        public JsonResult ObtenerAsientosReservados(string nombreDeLaActividad)
        {
            
            List<AsientoModel> asientosRelacionadosActividad = AccesoDatos.ObtenerAsientos(nombreDeLaActividad);
            List<int> reservados = new List<int>();
            for (int i = 0; i < asientosRelacionadosActividad.Count; i++)
            {
                AsientoModel asiento = asientosRelacionadosActividad[i];
                if (asiento.Reservado || asiento.Vendido)
                {
                    reservados.Add(i);
                }
            }
            return Json(reservados, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult BuscarActividad()
        {
            return View();
        }

        [HttpPost]
        public ActionResult BuscarActividad(string palabra)
        {
            
            ViewBag.actividadesUnicas = AccesoDatos.ObtenerActividadesPorBusqueda(palabra);
            return View();
        }

        [HttpGet]
        public ActionResult Inscribirme(string titulo)
        {
            
            DatosHandler datosHandler = new DatosHandler();
            ViewBag.paises = datosHandler.SelectListPaises();
            ViewBag.nivelesEducativos = datosHandler.SelectListNivelesEducativos();
            ViewBag.generos = datosHandler.SelectListGeneros();
            ViewBag.precio = AccesoDatos.ObtenerActividad(titulo).PrecioAproximado;
            ViewBag.titulo = titulo;
            return View();
        }

        [HttpPost]
        public ActionResult Inscribirme(InscripcionModel info)
        {
            ViewBag.exitoAlInscribir = false;
            try
            {
                if (ModelState.IsValid)
                {
                    ParticipanteHandler AccesoDatos = new ParticipanteHandler();
                    ActividadHandler actividad = new ActividadHandler();
                    bool estaAlmacenado = AccesoDatos.ParticipanteEstaAlmacenado(info.infoParticipante.correo);
                    if (!estaAlmacenado)
                        estaAlmacenado = AccesoDatos.AlmacenarParticipante(info.infoParticipante);
                    if (estaAlmacenado)
                        ViewBag.exitoAlInscribir = AccesoDatos.AlmacenarParticipacion(info.infoParticipante.correo, Request.Form["TituloActividad"], Double.Parse(Request.Form["PrecioActividad"]));

                    if (ViewBag.exitoAlInscribir)
                    {
                        ViewBag.Message = "Usted ha está inscrito en la actividad " + Request.Form["TituloActividad"];
                        ModelState.Clear();
                    }
                }
                return View();
            }
            catch
            {
                ViewBag.Message = "Algo salió mal.";
                return View();
            }
        }

        [HttpGet]
        public ActionResult VerFacturasDeActividad(string actividadNombre)
        {
            FacturasHandler AccesoDatos = new FacturasHandler();
            ViewBag.facturas = AccesoDatos.ObtenerFacturasDeActividad(actividadNombre);
            ViewBag.nombreActividad = actividadNombre;
            return View();
        }

        [HttpGet]
        public JsonResult ValidarCorreo(string correo)
        {
            ParticipanteHandler AccesoDatos = new ParticipanteHandler();
            bool existe = AccesoDatos.ParticipanteEstaAlmacenado(correo);
            if (existe)
            {
                var participante = AccesoDatos.ObtenerParticipante(correo);
                return Json(new{estaAlmacenado = true, infoPersonal = participante}, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new {estaAlmacenado = false, infoPersonal = ""}, JsonRequestBehavior.AllowGet);
            }
            
        }

        [HttpGet]
        public JsonResult ActualizarReservacionAsiento(int fila, int columna, string correo, bool reservado, string nombreActividad)
        {
            ActividadHandler accesoDatos = new ActividadHandler();
            bool exito = accesoDatos.ActualizarReservarAsiento(fila, columna, correo, reservado, nombreActividad);
            return Json(new {Exito = exito }, JsonRequestBehavior.AllowGet);
        }
    }
}

Planetario/Planetario/Views/Actividades/ComprarEntradas.cshtml
<link rel="stylesheet" href="~/Utils/css/SelectorAsientos.css">

<span class="titulo">@ViewBag.actividad.NombreActividad</span>
<p class="lead">Escoja sus entradas</p>
<div class="row" style="margin-top:5%;">
    <div class="col-6">
        <div id="map-container"></div>
        <div id="legend-container"></div>
    </div>
    <div class="col-6">
        <div id="cart-container"></div>
        <input type="submit" onclick="agregarAlCarrito()" class="btn btn-success btn-lg btn-lg" value="Agregar al carrito" data-bs-toggle="modal" data-bs-target="#exampleModal" />
    </div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-bs-backdrop="static" data-bs-keyboard="false" >
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-body">
                <h3>Entradas agregadas al carrito!</h3>
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Devolverme a actividades", "ListadoDeActividades", "Actividades", new { }, new { @class = "btn btn-danger btn-lg btn-lg" })
                @Html.ActionLink("Ir al carrito", "Carrito", "Ventas", new { }, new { @class = "btn btn-success btn-lg btn-lg" })
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="~/Utils/js/SelectorAsientos.js"></script>
<script>
    var sc;
    var nombreActividadVar = '@(ViewBag.actividad.NombreActividad)';
    @{ string linkAsientosReservados = Url.Content("~/Actividades/ObtenerAsientosReservados"); }
    fetch("@linkAsientosReservados" + "?nombreDeLaActividad=" + "@ViewBag.actividad.NombreActividad")
        .then(respuesta => {
            return respuesta.json()
        })
        .then(data => {
            var options = {
                map: {
                    id: 'map-container',
                    rows: 5,
                    columns: 10,
                    reserved: {
                        seats: data,
                    },
                    disabled: {
                    }
                },
                types: [
                    { type: "regular", backgroundColor: "#006c80", price: @ViewBag.Actividad.PrecioAproximado},
                ],
                cart: {
                    id: 'cart-container',
                    width: 280,
                    height: 250,
                    currency: '₡',
                },
                legend: {
                    id: 'legend-container',
                },
                assets: {
                    path: "/Utils/images/assets",
                }
            };

            sc = new Seatchart(options);


        })
    function agregarAlCarrito() {
        var carrito = sc.getCartDict().regular;
        var cantidadCarrito = carrito.length;
        console.log(cantidadCarrito);
        if (cantidadCarrito > 0) {
        $.getJSON('/Ventas/AgregarAlCarrito', { idComprable: @ViewBag.asientosRelacionadosActividad[0].IdComprable, cantidad: cantidadCarrito }, function (data) {
            console.log(data);
        });
        }
    }
</script>

Planetario/Planetario/Views/Actividades/buscarActividad.cshtml
@{
    ViewBag.Title = "Actividades";
}

<!DOCTYPE html>
<html>
<head>
    <title>Actividades</title>
    <meta charset="utf-8" />
    <link rel="stylesheet" type="text/css" href="~/Utils/css/main.css">
    <link rel="stylesheet" type="text/css" href="~/Utils/css/actividades.css">
    <link rel="stylesheet" type="text/css" href="~/Utils/css/botonesCompartir.css">
</head>
<body>

    <span class="titulo">Actividades</span>

    <form method="post" class="navbar-form navbar-right" action="@Url.Action("buscarActividad", "Actividades")">
        <div class="row">
            <div class="col-3 col-md-3 col-sm-2">
                <input type="text" name="palabra" class="form-control" placeholder="Buscar actividad">
            </div>
            <div class="col-3 col-md-3 col-sm-2">
                <button type="submit" class="btn btn-secondary"> <span class="fa fa-search" aria-hidden="true"></span> Buscar</button>
            </div>
        </div>
    </form>

    <div class="row d-flex flex-wrap align-items-center">
        @foreach (Planetario.Models.ActividadModel actividad in ViewBag.actividadesUnicas)
        {
            <div class="col-4">
                <div class="card">
                    <div class="card-header card-title">
                        @if (@actividad.Tipo == "Charla")
                        {
                            <i class="fa fa-commenting" aria-hidden="true"></i>
                        }
                        else
                        {
                            <i class="fa fa-book" aria-hidden="true"></i>
                        }
                        @actividad.NombreActividad
                    </div>
                    <div class="card-body">
                        <p class="card-text"><strong>Categoria: </strong>@actividad.Categoria</p>
                        <p class="card-text"><strong>Fecha: </strong>@actividad.Fecha</p>
                        <p class="card-text"><strong>Precio: </strong>₡@actividad.PrecioAproximado</p>
                    </div>
                    <a class="hidden stretched-link" href="@Url.Action("verActividad","Actividades", new { nombreDeLaActividad = actividad.NombreActividad.ToString() })"></a>
                </div>
            </div>
        }
    </div>
    <br /><br /><br />


</body>
</html>

Planetario/Planetario/Views/Actividades/crearActividad.cshtml
@model Planetario.Models.ActividadModel
@{
    ViewBag.Title = "Crear Actividad";
    List<SelectListItem> Categorias = new List<SelectListItem>() {
        new SelectListItem { Text = "Cuerpos del sistema solar", Value = "Cuerpos del sistema solar" },
        new SelectListItem { Text = "Objetos de Cielo Profundo", Value = "Objetos de Cielo Profundo"  },
        new SelectListItem { Text = "Astronomia", Value = "Astronomia" },
        new SelectListItem { Text = "General", Value = "General" },
    };

    List<SelectListItem> Complejidad = new List<SelectListItem>() {
        new SelectListItem { Text = "Simple", Value = "Simple" },
        new SelectListItem { Text = "Intermedio", Value = "Intermedio"  },
        new SelectListItem { Text = "Avanzado", Value = "Avanzado" },
    };
    List<SelectListItem> Publico = new List<SelectListItem>() {
        new SelectListItem { Text = "Niños", Value = "Niños" },
        new SelectListItem { Text = "Jóvenes", Value = "Jóvenes"  },
        new SelectListItem { Text = "Adultos", Value = "Adultos" },
        new SelectListItem { Text = "Adultos Mayores", Value = "Adultos Mayores" },
    };
    List<SelectListItem> Tipo = new List<SelectListItem>() {
        new SelectListItem { Text = "Taller", Value = "Taller" },
        new SelectListItem { Text = "Charla", Value = "Charla"  },
    };
}

<html>
<head>
    <style>
        body {
            background-color: #eee
        }
    </style>
    <meta charset="utf-8" />
    <link rel="stylesheet" type="text/css" href="~/Utils/css/main.css">
    <link rel="stylesheet" type="text/css" href="~/Utils/css/vistaPagos.css">
    <script src="https://cdn.jsdelivr.net/gh/minisuperfiles/MSFmultiSelect/msfmultiselect.min.js"></script>
    <link href="https://cdn.jsdelivr.net/gh/minisuperfiles/MSFmultiSelect/msfmultiselect.min.css" rel="stylesheet" />
</head>
<body>

    @using (Html.BeginForm("crearActividad", "Actividades", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <span class="titulo">Agregar Actividad</span>
        <h4>Ingrese los datos para crear una Actividad</h4>
        <p class="alert-success">@ViewBag.Message</p>
        <hr />
        <div class="card">
            <div class="row">
                <div class="col-6 col-md-4 col-sm-12">
                    <div class="form-floating">
                        @Html.TextBoxFor(model => model.NombreActividad, new { @class = "form-control", @placeholder = "Nombre" })
                        @Html.LabelFor(model => model.NombreActividad, htmlAttributes: new { @class = "control-label" })
                        @Html.ValidationMessageFor(model => model.NombreActividad, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-floating">
                        @Html.TextBoxFor(model => model.Duracion, new { @class = "form-control", @placeholder = "Nombre" })
                        @Html.LabelFor(model => model.Duracion, htmlAttributes: new { @class = "control-label" })
                        @Html.ValidationMessageFor(model => model.Duracion, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-floating">
                        @Html.TextBoxFor(model => model.PrecioAproximado, new { @class = "form-control", @placeholder = "Nombre" })
                        @Html.LabelFor(model => model.PrecioAproximado, htmlAttributes: new { @class = "control-label" })
                        @Html.ValidationMessageFor(model => model.PrecioAproximado, "", new { @class = "text-danger" })
                    </div>                   
             
                    <div class="form-floating">
                        @Html.TextBoxFor(model => model.Fecha, new { @type = "date", @class = "form-control datepicker" })
                        @Html.LabelFor(model => model.Fecha, htmlAttributes: new { @class = "control-label " })                     
                        @Html.ValidationMessageFor(model => model.Fecha, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="col-6 col-md-4 col-sm-12">
                    <div class="form-floating">
                        @Html.DropDownListFor(model => model.Complejidad, Complejidad, "", new { @class = "form-control", @placeholder = "Complejidad" })
                        @Html.LabelFor(model => model.Complejidad, htmlAttributes: new { @class = "control-label" })
                        @Html.ValidationMessageFor(model => model.Complejidad, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-floating">
                        @Html.DropDownListFor(model => model.PublicoDirigido, Publico, "", new { @class = "form-control", @placeholder = "PublicoDirigido" })
                        @Html.LabelFor(model => model.PublicoDirigido, htmlAttributes: new { @class = "control-label" })
                        @Html.ValidationMessageFor(model => model.PublicoDirigido, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-floating">
                        @Html.DropDownListFor(model => model.Tipo, Tipo, "", new { @class = "form-control", @placeholder = "Tipo" })
                        @Html.LabelFor(model => model.Tipo, htmlAttributes: new { @class = "control-label" })
                        @Html.ValidationMessageFor(model => model.Tipo, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-floating">
                        @Html.DropDownListFor(model => model.Categoria, Categorias, "", new { @id = "categoriaPregunta", @class = "form-control", @placeholder = "Categoria" })
                        @Html.LabelFor(model => model.Categoria, htmlAttributes: new { @class = "control-label" })
                        @Html.ValidationMessageFor(model => model.Categoria, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-4 col-sm-12">
                    <label for="myselect" class="control-label">Topicos</label>
                    <div id="myselect">
                        <select id="multiselect" name="others[]" multiple="multiple" class="form-control">
                        </select>
                    </div>
                    <input type="hidden" id="topicos" name="topicos" value="">                
                    <div class="form-floating">
                        @Html.TextAreaFor(model => model.Descripcion, new { @class = "form-control" })
                        @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label " })
                        @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-check form-switch">
                        @Html.Label("virtual", "¿Es virtual?")
                        @Html.CheckBox("virtual", false, htmlAttributes: new { @class = "form-check-input", @onclick = "addbox()" })
                    </div>
                    <div>
                        @Html.LabelFor(model => model.Link, htmlAttributes: new { @class = "control-label", @id = "areaLabel", style = "display : none;" })
                        @Html.TextBoxFor(model => model.Link, new { @class = "form-control", @id = "area", style = "display : none;" })
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 col-sm-12">
                @Html.ActionLink("Volver", "PanelDeAdministracion", "Home", new { area = "" }, new { @class = "btn btn-danger" })
            </div>
            <div class="col-md-4 col-sm-12">
                
            </div>
            <div class="col-md-4 col-sm-12">
                <input type="submit" class="btn btn-success" value="Crear" />
            </div>
        </div>
    }
    <div>
        @Html.ActionLink("Regresar a Inicio", "InformacionBasica", "Home")
    </div>

    <div style="margin-top:70px"></div>

    <script>

        function addbox() {
            if (document.getElementById('virtual').checked) {
                document.getElementById('area').style.display = 'block';
                document.getElementById('areaLabel').style.display = 'block';
            } else {
                document.getElementById('area').style.display = 'none';
                document.getElementById('areaLabel').style.display = 'none';
            }
        }
    </script>
    <script>
        let select = new MSFmultiSelect(
            document.querySelector('#multiselect'),
            {
                theme: 'theme2',
                selectAll: false,
                searchBox: false,
                width: 280,
                height: 50,
                onChange: function (checked, value, instance) {
                    listar();
                },
                placeholder: 'Topicos',
                afterSelectAll: function (checked, values, instance) {

                }
            }
        );

        function listar() {
            let seleccion = [];
            let topicos = document.getElementById("multiselect").options;
            for (let i = 0; i < topicos.length; i++) {
                if (select.data[i] === true) {
                    seleccion.push(topicos[i].value)
                }
            }
            document.getElementById("topicos").value = seleccion.join(";");
            console.log(document.getElementById("topicos").value)
        }
    </script>
    <script type="text/javascript">
        $('#categoriaPregunta').change(function () {
                var categoriaSeleccionada = $(this).val();
                if (categoriaSeleccionada != null && categoriaSeleccionada != '') {
                    $.getJSON('@Url.Action("../Topicos/ConseguirTopicos")', { categoria: categoriaSeleccionada }, function (topicos) {
                        var topicoSeleccionado = $('#multiselect');
                        topicoSeleccionado.empty();
                        $.each(topicos, function (index, topico) {
                            if (index != 0) {
                                topicoSeleccionado.append($('<option/>', {
                                    value: topico.Value,
                                    text: topico.Text
                                }));
                            }
                        });
                        select.reload();
                    });
                }
            });
    </script>

</body>
</html>

Planetario/Planetario/Views/Actividades/listadoDeActividades.cshtml
@{
    ViewBag.Title = "Actividades";
}

<!DOCTYPE html>
<html>
<head>
    <title>Actividades</title>
    <meta charset="utf-8" />
    <link rel="stylesheet" type="text/css" href="~/Utils/css/main.css">
    <link rel="stylesheet" type="text/css" href="~/Utils/css/actividades.css">
    <link rel="stylesheet" type="text/css" href="~/Utils/css/botonesCompartir.css">
</head>
<body>

    <span class="titulo">Actividades</span>

    <form method="post" class="navbar-form navbar-right" action="@Url.Action("buscarActividad", "Actividades")">
        <div class="row">
            <div class="col-3 col-md-3 col-sm-2">
                <input type="text" name="palabra" class="form-control" placeholder="Buscar actividad">
            </div>
            <div class="col-3 col-md-3 col-sm-2">
                <button type="submit" class="btn btn-secondary"> <span class="fa fa-search" aria-hidden="true"></span> Buscar</button>
            </div>
        </div>
    </form>

    <div class="row d-flex flex-wrap align-items-center">
        @foreach (Planetario.Models.ActividadModel actividad in ViewBag.actividades)
        {
            <div class="col-4">
                <div class="card">
                    <div class="card-header card-title">
                        @if (@actividad.Tipo == "Charla")
                        {
                            <i class="fa fa-commenting" aria-hidden="true"></i>
                        }
                        else
                        {
                            <i class="fa fa-book" aria-hidden="true"></i>
                        }
                        @actividad.NombreActividad
                    </div>
                    <div class="card-body">
                        <p class="card-text"><strong>Categoria: </strong>@actividad.Categoria</p>
                        <p class="card-text"><strong>Fecha: </strong>@actividad.Fecha</p>
                        <p class="card-text"><strong>Precio: </strong>₡@actividad.PrecioAproximado</p>
                    </div>
                    <a class="hidden stretched-link" href="@Url.Action("verActividad","Actividades", new { nombreDeLaActividad = actividad.NombreActividad.ToString() })"></a>
                </div>
            </div>
        }
    </div>
    <br /><br /><br />


</body>
</html>

Planetario/Planetario/Views/Actividades/verFacturasDeActividad.cshtml
<!DOCTYPE html>
<html>
<head>
</head>
<body>
<h1 class=titulo>Facturas de @ViewBag.nombreActividad</h1>
<div class="row d-flex flex-wrap align-items-center">
    @foreach (Planetario.Models.FacturaModel factura in ViewBag.facturas)
    {
        <div class="col-md-6">
        <h4>@factura.correoCliente</h4>
        <p><strong>Id de la factura:</strong> @factura.id</p>
        <p><strong>Fecha:</strong> @factura.fecha</p>
        <p><strong>Pago: </strong>@factura.pago colones</p>
        <br><br>
        </div>
    }
</div>
</body>
</hmtl>