Planetario/Planetario/Controllers/FuncionariosController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Planetario.Handlers;
using Planetario.Models;

namespace Planetario.Controllers
{
    public class FuncionariosController : Controller
    {
        public ActionResult ListaFuncionarios()
        {
            FuncionariosHandler AccesoDatos = new FuncionariosHandler();
            ViewBag.ListaFuncionarios = AccesoDatos.ObtenerTodosLosFuncionarios();
            return View();
        }

        [HttpGet]
        public ActionResult ObtenerImagen(string correo)
        {
            FuncionariosHandler productHandler = new FuncionariosHandler();
            var tupla = productHandler.ObtenerFoto(correo);
            return File(tupla.Item1, tupla.Item2);
        }


        public ActionResult VerFuncionario(string correo)
        {
            FuncionariosHandler AccesoDatos = new FuncionariosHandler();
            ViewBag.Funcionario = AccesoDatos.ObtenerFuncionario(correo);
            ViewBag.Idiomas = AccesoDatos.ObtenerIdiomasFuncionario(correo);
            ViewBag.Titulos = AccesoDatos.ObtenerTitulosFuncionario(correo);
            ViewBag.Roles = AccesoDatos.ObtenerRolesFuncionario(correo);

            return View();
        }

        [HttpGet]
        public ActionResult AgregarFuncionario()
        {
            DatosHandler dataHandler = new DatosHandler();
            ViewBag.paises = dataHandler.SelectListPaises();
            ViewBag.generos = dataHandler.SelectListGeneros();
            ViewBag.opcionIdiomas = obtenerIdiomas();
            return View();
        }

        [HttpPost]
        public ActionResult AgregarFuncionario(FuncionarioModel funcionario, string idiomas)
        {
            List<SelectListItem> opcionIdiomas = new List<SelectListItem>();
            opcionIdiomas = obtenerIdiomas();
            ViewBag.opcionIdiomas = opcionIdiomas;

            ViewBag.ExitoAlCrear = false;
            try
            {
                if (ModelState.IsValid)
                {
                    FuncionariosHandler accesoDatos = new FuncionariosHandler();

                    string[] idioma = idiomas.Split(';');
                    List<string> idiomasSelect = new List<string>(idioma);

                    ViewBag.ExitoAlCrear = accesoDatos.InsertarFuncionario(funcionario);
                    if (ViewBag.ExitoAlCrear)
                    {
                        ViewBag.Message = "El funcionario "  + funcionario.nombre + " fue agregado con éxito.";
                        foreach(var variable in idiomasSelect)
                        {
                            accesoDatos.InsertarIdiomas(variable, funcionario.correo);
                        }
                        ModelState.Clear();
                    }
                }
                return View();
            }
            catch
            {
                ViewBag.Message = "Algo salió mal ";
                return View();
            }
        }

        public List<SelectListItem> obtenerIdiomas()
        {
            EstadisticasHandler accesoDatos = new EstadisticasHandler();

            var idiomas = accesoDatos.obtenerListaIdiomas();


            List<SelectListItem> listaIdiomas = new List<SelectListItem>();
            string todos = "Todos";

            for (int i = 0; i < idiomas.Count(); i++)
            {
                listaIdiomas.Add(new SelectListItem()
                {
                    Text = idiomas[i],
                    Selected = (idiomas[i] == todos ? true : false)
                });
            }

            return listaIdiomas;
        }
    }
}

Planetario/Planetario/Views/Funcionarios/AgregarFuncionario.cshtml
@model Planetario.Models.FuncionarioModel
@{
    ViewBag.Title = "Agregar Funcionario";
    List<SelectListItem> generos = ViewBag.generos;
    List<SelectListItem> paises = ViewBag.paises;
}

<html>
<head>
    <link rel="stylesheet" type="text/css" href="~/Utils/css/main.css">
    <script src="https://cdn.jsdelivr.net/gh/minisuperfiles/MSFmultiSelect/msfmultiselect.min.js"></script>
    <link href="https://cdn.jsdelivr.net/gh/minisuperfiles/MSFmultiSelect/msfmultiselect.min.css" rel="stylesheet" />
</head>
<body>
    @using (Html.BeginForm("AgregarFuncionario", "Funcionarios", FormMethod.Post, new { enctype = "multipart/form-data", onsubmit = "listar()" }))
    {
        <span class="titulo">Agregar Funcionario</span>
        <p class="alert-success">@ViewBag.Message</p>
        <h4> Formulario de agregar funcionarios</h4>
        <hr />

        <div class="row">
            <div class="col-md-4 col-sm-12">
                @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label" })
                <div>
                    @Html.TextBoxFor(model => model.nombre, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
                </div>

                @Html.LabelFor(model => model.apellido1, htmlAttributes: new { @class = "control-label" })
                <div>
                    @Html.TextBoxFor(model => model.apellido1, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.apellido1, "", new { @class = "text-danger" })
                </div>

                @Html.LabelFor(model => model.apellido2, htmlAttributes: new { @class = "control-label" })
                <div>
                    @Html.TextBoxFor(model => model.apellido2, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.apellido2, "", new { @class = "text-danger" })
                </div>

                @Html.LabelFor(model => model.correo, htmlAttributes: new { @class = "control-label" })
                <div>
                    @Html.TextBoxFor(model => model.correo, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.correo, "", new { @class = "text-danger" })
                </div>

                @Html.LabelFor(model => model.Contrasena, htmlAttributes: new { @class = "control-label" })
                <div>
                    @Html.TextBoxFor(model => model.Contrasena, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Contrasena, "", new { @class = "text-danger" })
                </div>
                @Html.LabelFor(model => model.areaExpertis, htmlAttributes: new { @class = "control-label" })
                <div>
                    @Html.TextBoxFor(model => model.areaExpertis, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.areaExpertis, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="col-md-4 col-sm-12">

                @Html.LabelFor(model => model.fechaIncorporacion, htmlAttributes: new { @class = "control-label" })
                <div>
                    @Html.TextBoxFor(model => model.fechaIncorporacion, new { @type = "date", @class = "form-control datepicker" })
                    @Html.ValidationMessageFor(model => model.fechaIncorporacion, "", new { @class = "text-danger" })
                </div>

                @Html.LabelFor(model => model.pais, htmlAttributes: new { @class = "control-label" })
                <div>
                    @Html.DropDownListFor(model => model.pais, paises, "-País-", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.pais, "", new { @class = "text-danger" })
                </div>

                @Html.LabelFor(model => model.genero, htmlAttributes: new { @class = "control-label" })
                <div>
                    @Html.DropDownListFor(model => model.genero, generos, "-Selección-", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.genero, "", new { @class = "text-danger" })
                </div>

                <label for="myselect" class="control-label">Idiomas</label>
                <div id="myselect">
                    <select id="multiselect" name="others[]" multiple="multiple" class="form-control">

                        @foreach (var idioma in ViewBag.opcionIdiomas)
                        {
                            <option value=@idioma.Text>@idioma.Text</option>
                        }

                    </select>
                </div>
                <input type="hidden" id="idiomas" name="idiomas" value="">
            </div>
            <div class="col-md-4 col-sm-12">
                @Html.LabelFor(model => model.FotoArchivo, htmlAttributes: new { @class = "control-label" })
                <div>
                    @Html.TextBoxFor(model => model.FotoArchivo, new { type = "file", @class = "btn btn alert-info" })
                    @Html.ValidationMessageFor(model => model.FotoArchivo, "", new { @class = "text-danger" })
                </div>

                @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label" })
                <div>
                    @Html.TextAreaFor(model => model.descripcion, new { @class = "form-control", @rows = 5, @cols = 80 })
                    @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-1 col-md-4 col-sm-2">
                <input type="submit" class="btn btn-success" value="Agregar" />
            </div>
            <div class="col-1 col-md-4 col-sm-2">
                @Html.ActionLink("Volver", "ListaFuncionarios", null, new { @class = "btn btn-danger" })
            </div>
        </div>


    }
    <div>
        @Html.ActionLink("Regresar a Inicio", "InformacionBasica", "Home")
    </div>

    <script>
        let listaIdiomas = @Html.Raw(Json.Encode(ViewBag.opcionIdiomas));
        let select = new MSFmultiSelect(
            document.querySelector('#multiselect'),
            {
                theme: 'theme2',
                selectAll: false,
                searchBox: false,
                width: 280,
                height: 50,
                onChange: function (checked, value, instance) {
                    listar();
                },
                placeholder: 'idiomas',
                afterSelectAll: function (checked, values, instance) {

                }
            }
        );

        function listar()
        {
            var seleccion = [];

            for (i = 0; i < listaIdiomas.length; i++) {
                if (select.data[i] === true) {
                    seleccion.push(listaIdiomas[i].Text)
                }
            }
            document.getElementById("idiomas").value = seleccion.join(";");

        }
    </script>
</body>
@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}
</html>

Planetario/Planetario/Views/Funcionarios/ListaFuncionarios.cshtml
@model Planetario.Models.FuncionarioModel
@{
    var listaFuncionarios = ViewBag.listaFuncionarios;
    var cantidadFuncionarios = ViewBag.listaFuncionarios.Count;
}
<head>
    <link href="~/Styles/ListaFuncionarios.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" href="~/Utils/css/main.css">
</head>
<span class="titulo">
    Funcionarios
</span>

<style>
    .cuadroFuncionario {
        margin-bottom: 10px;
        padding: 1em;
    }
    img {
        border-radius: 0.5em;
        border: 2px solid #133b5c;
        box-shadow: 0px 0px 0px #ccc;
        height:180px;
        width:180px;
        object-fit:cover;
    }
</style>

<div class="row d-flex flex-wrap align-items-center">
    @foreach (var funcionario in ViewBag.ListaFuncionarios)
    {
        <div class="cuadroFuncionario row d-flex flex-wrap align-items-center col-md-6">
            <div class="imagenFuncionario col-md-4">
                <img src=@Url.Action("ObtenerImagen", "Funcionarios", new { correo = funcionario.correo })>
            </div>
            <div class="textoFuncionario col-md-8">
                <h3>@funcionario.nombre @funcionario.apellido1 @funcionario.apellido2</h3>
                <p>@funcionario.correo</p>
                <p>@funcionario.areaExpertis</p>
                @Html.ActionLink("Ver más", "verFuncionario", "Funcionarios", new { correo = @funcionario.correo.ToString() }, null)
                <br />
            </div>
        </div>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Planetario/Planetario/Views/Funcionarios/VerFuncionario.cshtml
@model Planetario.Models.FuncionarioModel
@{
    var listaFuncionarios = ViewBag.listaFuncionarios;
}
<head>
    <link href="~/Styles/ListaFuncionarios.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" href="~/Utils/css/main.css">
</head>

<style>
    img {
        border-radius: 0.5em;
        border: 2px solid #133b5c;
        box-shadow: 0px 0px 0px #ccc;
        height: 400px;
        width: 400px;
        object-fit: cover;
    }
</style>

<body>
    <span class="titulo">
        @ViewBag.Funcionario.nombre @ViewBag.Funcionario.apellido1 @ViewBag.Funcionario.apellido2
    </span>

    <div class="row d-flex flex-wrap align-items-center">




        <div class="col-md-4">
            <img src=@Url.Action("ObtenerImagen", "Funcionarios", new { correo = @ViewBag.Funcionario.correo })>
        </div>
        <div class="col-md-4">
            <h4>Contacto</h4>
            <p>@ViewBag.Funcionario.correo</p>
            <br />

            <h4>Información personal</h4>
            <p>Pais: @ViewBag.Funcionario.pais</p>
            <p>Genero: @ViewBag.Funcionario.genero</p>
            <br />

            <h5>Información profesional</h5>
            <p>Area Expertis: @ViewBag.Funcionario.areaExpertis</p>
            <p>Fecha Incorporacion: @ViewBag.Funcionario.fechaIncorporacion</p>
        </div>
        <div class="col-md-4">
            @if (ViewBag.idiomas.Count > 1)
            {
                <h4>Idiomas</h4>
            }
            else
            {
                <h4>Idioma</h4>
            }
            @foreach (var idioma in ViewBag.idiomas)
            {
                <p>- @idioma</p>
            }
            <br />
            @if (ViewBag.titulos.Count > 1)
            {
                <h4>Títulos</h4>
            }
            else
            {
                <h4>Título</h4>
            }
            @foreach (var titulo in ViewBag.titulos)
            {
                <p>- @titulo</p>
            }
            <br />
            @if (ViewBag.roles.Count > 1)
            {
                <h4>Roles</h4>
            }
            else
            {
                <h4>Rol</h4>
            }
            @foreach (var roles in ViewBag.roles)
            {
                <p>- @roles</p>
            }
        </div>
    </div>

    <br />

    <h4>Descripción</h4>
    <p>@ViewBag.Funcionario.descripcion</p>

    <div style="margin-top:100px"></div>

</body>

Planetario/Planetario/Views/Funcionarios/iniciarSesion.cshtml
@model Planetario.Models.FuncionarioModel

@{
    ViewBag.Title = "InicioSesion";
}

<!DOCTYPE html>
<html>
<head>
    <title>Login V1</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" href="~/Utils/images/icons/favicon.ico" />
    <link rel="stylesheet" type="text/css" href="~/Utils/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="~/Utils/vendor/animate/animate.css">
    <link rel="stylesheet" type="text/css" href="~/Utils/vendor/css-hamburgers/hamburgers.min.css">
    <link rel="stylesheet" type="text/css" href="~/Utils/vendor/select2/select2.min.css">
    <link rel="stylesheet" type="text/css" href="~/Utils/css/util.css">
    <link rel="stylesheet" type="text/css" href="~/Utils/css/main.css">
</head>
<body>

    <div class="limiter">
        <div class="wrap-login100">
            <div class="login100-pic js-tilt" data-tilt>
                <img src="~/Utils/images/img-01.png" alt="IMG">
            </div>

            @using (Html.BeginForm())
            {
                <div class="login100-form validate-form">
                    @Html.AntiForgeryToken()
                    <span class="login100-form-title">
                        Ingrese sus datos
                    </span>

                    <div class="wrap-input100 validate-input" data-validate="Valid email is required: ex@abc.xyz">
                        @Html.TextBoxFor(model => model.correo, new { @class = "input100", placeholder = "Correo eletrónico" })
                        <span class="focus-input100"></span>
                        <span class="symbol-input100">
                            <i class="fa fa-envelope" aria-hidden="true"></i>
                        </span>
                    </div>

                    <div class="wrap-input100 validate-input" data-validate="Password is required">
                        @Html.PasswordFor(model => model.Contrasena, new { @class = "input100", placeholder = "Contraseña" })
                        <span class="focus-input100"></span>
                        <span class="symbol-input100">
                            <i class="fa fa-lock" aria-hidden="true"></i>
                        </span>
                    </div>

                    <div class="container-login100-form-btn">
                        <button class="login100-form-btn" type="submit">
                            Login
                        </button>
                    </div>

                    <div class="text-center p-t-12">
                        <a class="txt2" href="/Home/InformacionBasica">
                            Volver al Inicio
                            <i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
                        </a>
                    </div>
                </div>
            }

        </div>

    </div>

    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>

    <script src="~/Utils/vendor/jquery/jquery-3.2.1.min.js"></script>
    <script src="~/Utils/vendor/bootstrap/js/popper.js"></script>
    <script src="~/Utils/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/Utils/vendor/select2/select2.min.js"></script>
    <script src="~/Utils/vendor/tilt/tilt.jquery.min.js"></script>
    <script>
        $('.js-tilt').tilt({
            scale: 1.1
        })
    </script>
    <script src="~/Utils/js/main.js"></script>
</body>
</html>